using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpawnTile : MonoBehaviour
{
    [SerializeField] float destroyDelay;

    private void OnTriggerStay2D(Collider2D collision)
    {
        if (collision.TryGetComponent(out Base_Enemy enemy))
        {
            Destroy(enemy.gameObject, destroyDelay);
            GameManager.Instance.UpdateStatsOnEnemyOutOfGameArea();
        }
    }

    //private void OnTriggerEnter2D(Collider2D collision)
    //{
    //    if (collision.TryGetComponent(out Base_Enemy enemy))
    //    {
    //        Destroy(enemy.gameObject, destroyDelay);
    //        GameManager.Instance.UpdateStatsOnEnemyOutOfGameArea();
    //    }
    //}
}
